---
title: "Peak-Erkennung und Annotierung mit ntsworkflow"
author: "Referat G2 (Gewässerchemie), Bundesanstalt für Gewässerkunde, Koblenz"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Peakerkennung_Annotierung_de}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Anleitung

Nachdem das Paket mit `library(ntsworkflow)` geladen wurde, kann durch den Befehl `runPeakPicking()` die Datenauswertung gestartet werden.

### Auswahl der MS-Daten für die Verarbeitung

Zunächst müssen die LC/GC-HRMS Daten in ein `*.mzML` oder `*.mzXML` Format gebracht werden. Für eine optimale Darstellung sollten nur gewichtete (Flächenschwerpunkt) Spektren (Engl.: centroid spectra)  genutzt werden. `ntsworkflow` wurde erstellt um mit MS und MS^2^ Spektren zu arbeiten, wobei MS^2^ Spektren im Datenabhängigen Modus (DDA) aufgenommen werden sollen. 
Um die Rohdaten auszuwählen klicken Sie auf `Add Sample` und nutzen Sie den Dialog. Sie können mehr als eine Datei durch Halten von Strg oder Umschalt auswählen. Der Dialog wird sich immer im derzeitigen R-Arbeitsverzeichnis öffnen.
Die Dateien werden in den Arbeitsspeicher geladen. Also seien Sie vorsichtig, dass Sie nicht zu viele Dateien gleichzeitig bearbeiten, denn sonst wird der System RAM überladen. Sollte der Arbeitsspeicher nicht ausreichen um alle ihre Dateien zu bearbeiten, nutzen Sie stattdessen [`Batch Process`](#batch).

### Betrachten der Dateien

Im Reiter „Sample info“ erhält man grundlegende Informationen über die links in der Probentabelle ausgewählte Probe.  Hier kann der Dateipfad manuell geändert werden, die Probe aus dem RAM entfernt oder in selbigen geladen werden. Ebenso können Proben hier gelöscht werden. Und man kann in einem Auswahlmenü wählen um welchen Typ es sich bei der Probe handelt. 
Ob eine Probe in den RAM geladen ist oder nicht erkennt man mit einem Blick in die Probentabelle. Grün bedeutet die Datei ist aktiv im Arbeitsspeicher, rot steht für das Gegenteil.
Einen weiteren ersten Überblick liefern die Reiter `TIC` oder `XIC`. Hierfür wird links wieder eine Probe ausgewählt und dann kann ein spezifisches m/z Verhältnis mit Toleranz ausgewählt werden, welches dann extrahiert wird.

### Speichern und Laben

Den Workspace kann mit "Save" unter der Probentabelle gesichert werden (Daten werden als mehrere Tabellen gespeichert). Mit "Load" kann man ein bereits gespeichertes Workspace laden (.ntr Datei).   

### Peak-picking

Um das Peak-Picking zu starten wählen Sie den `Peak Picking/Parameters` Reiter aus. Hier finden sich einige Einstellungen, welche festgelegt und für die jeweilige LC oder GC Methode optimiert werden können.

#### Parameters

#### Mass range m/z, RT range (min)

Hier wird der Bereich für m/z und RT festgelegt in welchem der Algorithmus nach Peaks suchen soll.

##### m/z step

Hierbei handelt es sich um den „Binning-Step“, also die Größe der festgelegten Intervalle in welchem sich der Algorithmus bewegen soll um ein EIC (extrahiertes Ionen Chromatogramm) zu erstellen. Ein m/z Schritt von 0.02 bei der Startmasse 100 bedeutet, dass die Berechnung des EIC bei 100.0000 beginnt und bei 100.0200 endet. Dieses EIC wird dann genutzt um nach Peaks zu suchen. Je größer die m/z Schritte sind desto schneller erfolgt die Verarbeitung, da weniger EICs für den gewählten Massenbereich gesucht werden müssen. Die Auswahl einer zu großen Schrittweite kann allerdings zu verrauschten EICs oder überlappenden Peaks führen. Beides macht das Auswerten deutlich schwieriger.
Wenn Sie eine der Dateien in der Probentabelle links auswählen, wird Ihnen, basierend auf der Auflösung der Daten, ein Wert für den m/z Schritt vorgeschlagen. Bitte testen Sie an dieser Stelle verschiedene Werte und optimieren sie so das „Peak Picking“ für ihre eigenen Dateien.

##### Min. Intensity

Peaks unter dieser Intensität werden nicht weiter berücksichtigt. Dabei entscheidet die Höhe des höchsten gewichteten Spektrums über die angegebene Intensität.
Die mindest Intensität kann auch dynamisch für jede einzelne Probe gewählt werden. Hierfür kann der interne Standard dienen. Um diese Einstellungsmöglichkeit zu nutzen, aktivieren Sie `Derive min. intensity from internal standard`, geben Sie die passende Masse und Retentionszeit (mit Toleranzen) für den IS Peak an und teilen Sie der Applikation mit wie die mindest Intensität (relativ zu diesem Peak) gesetzt werden soll. *Note:* Blindwertproben müssen ebenfalls mit internen Standard versetzt sein.   

##### S/N

Peaks mit einem Signal-zu-Rauschen Verhältnis unter diesem Wert werden nicht berücksichtigt.

##### Noise (scans)

Legt die Anzahl von MS scans fest, die vor und nach dem chromatografischen Peak zur Bestimmung des Rauschpegels herangezogen werden sollen. Dieser Wert sollte groß genug sein um eine gute Einschätzung des Rauschpegels geben zu können.

##### Max peaks per peak

Hiermit wird festgelegt, wie viele kleine Spitzen einen Peak haben darf. Bei sehr verrauschte Chromatogramme kann es sein, dass diesen Wert erhoht werden muss. Allerdings einen zu hohen Wert kann die Anzahl Falschpositiven erhöhen.  

##### Peak width (sec)

Peaks mit einer Breite an der Basis, die außerhalb dieses Bereichs liegen, werden nicht berücksichtigt.

##### Peak picking/Parameter

Dies ist der eigentliche Startbefehl für das „Peak Picking“. Dabei kann man sich entscheiden ob nur eine Datei (nämlich die in der Probentabelle ausgewählte) oder alle Dateien verarbeitet werden sollen.
Auch wenn der gesamte Datensatz schon durchsucht wurde kann man hier noch einmal nachträglich eine Probe durch das „Peak Picking“ schicken. Dies wird u.a. dafür genutzt einen Blindwert mit einer geringeren Mindestintensität als die restlichen Proben zu verarbeiten. 
Wenn alles eingestellt ist, startet `Pick Peaks` die Verarbeitung.
Den Fortschritt über allen Proben können sie unten rechts verfolgen.

### Batch processing  {#batch}

Für den Fall, dass Sie einen besonders großen Datensatz bearbeiten wollen, können Sie den „Batch“ Modus nutzen.  In diesem Fall sollten erst alle Einstellungen im Reiter `Peak Picking` und `Alignment/Table` angepasst werden.
Wenn dies geschehen ist können die Daten für die Bearbeitung wie folgt ausgewählt werden:
Klicken Sie auf die Schaltfläche `Batch Process` und dann auf `Add files`. Es erscheint ein Dialogfenster in welchem Sie die gewünschten Dateien auswählen. Durch Halten von Strg oder Umschalt können mehrere Dateien auf einmal angewählt werden. Um Dateien wieder zu entfernen benutzen sie die Schaltfläche `Remove Files`. Um den Probentyp (Unknown, Standard, Blank) zu wählen klicken Sie in der entsprechenden Reihe auf den  „Sample Type“. Falls sie eine oder mehrere Proben doch in den RAM laden wollen können sie den Befehl hierfür in der dazugehörigen Spalte, durch klicken, geben.
Es gibt überdies noch die Möglichkeit hier eine Schaltfläche zu aktivieren, die dafür sorgt, dass der Blindwert mit 1/10 der Mindestintensität der restlichen Proben verarbeitet werden soll.
Wenn alles eingestellt ist, startet die Schaltfläche `Go` die Verarbeitung. Proben werden gepickt und anschließend mit einander verschnitten (Alignment). 
Den Fortschritt können sie unten rechts verfolgen.

#### Peak Picking/Data

In diesem Reiter finden Sie eine Zusammenstellung der generierten Peaklisten. Links lässt sich markieren welche Probe betrachtet werden soll. In der erste Spalte der Tabelle sieht man die gefundenen Massen, rechts daneben bei welcher Retentionszeit in Minuten) diese gefunden wurde. Daneben die Intensität, gefolgt von der Peakfläche und in der letzten Spalte schließlich das Signal-zu-Rauschen Verhältnis.
Über der Tabelle befinden sich verschiedene Reiter. `All` zeigt alle gefundenen Peaks, `Cl` nur die dazugehörigen Chlor Isotope einer zuvor markierten Masse, `Br` die Brom-Isotope. Durch `Hide false positive` können als falschpositiven markierte Peaks versteckt werden. Um diese zu markieren, wählen Sie einen Eintrag der Peakliste aus und drücken sie die Taste „Entf“, die komplette Zeile wird gelb hinterlegt. Um diesen Schritt wieder rückgängig zu machen drücken sie die Taste „Einfg“.
Unter der Tabelle können sie genau Werte eingeben bzw. Wertebereiche bestimmen um die Tabelle zu filtern (so: `137.2...137.4`).  
Rechts neben der Tabelle finden sie, bei einer im RAM geladenen Datei, drei Diagramme.

##### XIC

Das Extrahierte Ionen Chromatogramm der ausgewählten Masse können sie hier betrachten. Mit der Maus kann ein Bereich im Diagramm markiert werden und so der Ausschnitt des Chromatogramms vergrößert werden. Doppelklick mit der linken Maustaste versetzt das Diagramm wieder in die Ursprungsversion.

##### MS1

Hier können sie das MS1 Spektrum der ausgewählten Masse betrachten.

##### MS2

Das MS2 Spektrum der ausgewählten Massen kann hier angesehen werden. Beim Anklicken bekommt man eine Tabelle der Fragmente, die durchs Markieren und strg+c kopiert weren kann für den Eintrag in MetFrag oder ähnliches.  

#### Components

In diesem Reiter werden alle Massen, die einander zugeordnet werden können zusammen gefügt. Der Algorithmus betrachtet hier verschiedene Punkte um diese Zuordnung vonstatten gehen zu lassen. Dabei werden die Massenspuren über die Messzeit und die Peakform miteinander vergleichen. 
Wenn es der Applikation möglich ist gibt sie in der rechten Tabelle auch direkt an um welche Komponente es sich handelt. (z.B. 13C)

### Alignment

“Features” werden, über alle Dateien, durch betätigen der Schaltfläche `Align Features` abgeglichen. Dabei betrachtet der Algorithmus zunächst das erste „Feature“ der ersten Probe und untersucht anschließend alle folgenden Proben auf dieses „Feature“. Dabei bewegt sich der Algorithmus innerhalb der festgelegten Toleranzen für Masse und Retentionszeit. 
Aus all diesen Kandidaten wird nun der intensivste genommen und der erste Schritt wiederholt. Denn es wird angenommen, dass der intensivste Peak die Masse und Retentionszeit am genauesten abbildet. Anschließend wird mit den verbleibenden, noch nicht abgeglichenen „Features“ genauso vorgegangen, bis alle „Features“ in allen Proben verbunden worden sind.
Das fertige Ergebnis wird in der „Alignment-Tabelle“ dargestellt. Hierbei wird ein die mittlere m/z und Retentionszeit in den ersten beiden Spalten gezeigt und darauffolgend die Intensität des „Features“ in den verschiedenen Proben. Ein Klick auf die entsprechende Reihe zeigt Ihnen die überlappenden EICs, den Intensitätsverlauf und das überlappende MS^2^ Spektrum.

23.07.2019
Der Paramter `MS2 m/z Tol. (ppm):` wird zur Zeit nicht benutzt und hat keinerlei Einfluss.

### Normalization

Die Intensität aller „Features“  kann durch einen internen Standard normalisiert werden.  Zunächst wird der interne Standard über seine Masse und Retentionszeit ausgewählt und dann die `Normalize` Schaltfläche gedrückt. Die Intensitäten in der „Alignment-Tabelle“  werden neu kalkuliert und für jedes einzelne „Feature“ in jeder einzelnen Probe durch die Intensität des internen Standards dividiert.

Um die “Alignment-Tabelle” wieder in den ursprünglichen Zustand zu versetzten, drücken Sie `Align Features` erneut.

### Blank correction

Durch Klicken auf `Blank Correction` werden die „Features“, die ebenfalls in den Blindwertproben gefunden worden sind, aus der „Alignment-Tabelle“ entfernt. Proben können, wie eingangs erwähnt, im Reiter `Sample info` unter `sample type` definiert werden.
„Features“, die bei dem Vergleich zwischen Probe und Blindwert, eine 10x höhere Intensität aufweisen werden beibehalten. Dieser `Blank factor` kann geändert werden.
Um die “Alignment-Tabelle” wieder in den ursprünglichen Zustand zu versetzten, drücken Sie `Align Features` erneut.

### Weitere Filter der “Alignment-Tabelle” 

Auch diese Filter reduzieren die Größe der “Alignment-Tabelle”.  Der Oberste Filter entfernt Reihen, in welchen die Trefferrate zu gering ist. Die anderen Filter bedürfen einer längeren Erklärung, welche nun folgt. 
Um die “Alignment-Tabelle” wieder in den ursprünglichen Zustand zu versetzten, drücken Sie `Align Features` erneut.

#### Remove features which are not the highest in their component

Dieser Filter durchsucht die “Alignment-Tabelle” und prüft ob das abgeglichene „Feature“ niemals das intensivste „Feature“ eine Komponente ist. Wenn das der Fall ist, wird das „Feature“ entfernt.
In anderen Worten ausgedrückt: Ist das „Feature“ in einer oder mehreren  Proben das intensivste seiner Komponenten wird das „Feature“ nicht entfernt.
Um Proben für diesen Vorgang auszuwählen müssen Sie diese in der Form „1:10“ angeben. Z.B. können so alle Proben ausgewählt werden und ganze Zeilen gelöscht werden.
Um die “Alignment-Tabelle” wieder in den ursprünglichen Zustand zu versetzten, drücken Sie `Align Features` erneut.

#### Remove features which are not found in replicate injections

Wurde ein “Feature” nicht in einem Replikat Injektion gefunden, dann wird die Intensität auf Null gesetzt.  
Die zu berücksichtigenden Proben werden erneut in der Form „1:10“ angegeben. Anschließend wird die Zahl der Replikate (die Anzahl der Proben muss durch die Anzahl der Replikate teilbar sein)  und wie oft eine „Feature“ erkannt werden soll genannt. Um ein  Beispiel zu nennen: Sie haben 2 Proben, die je 3 mal gemessen worden sind und sie wollen, dass ein „Feature mindestens in 2 der 3 Replikate gefunden wurde, dann schreiben Sie: „files to consider“  ist 1:6, „No. of replicates“ ist 3 und im Feld „In at last“ 2.

Reihen in denen diese Bedingungen nicht erfüllt worden sind bekommen eine Intensität von Null und werden entfernt.

#### Get average intensity of features in replicates

Durch diesen Filter werden keine Reihen, sondern Spalten entfernt. Dieser Parameter wirkt ähnlich wie der zuvor genannte, nur wird in diesem Fall die Mittlere Intensität aller „Features“ in den Replikaten berechnet. Dabei werden Intensitäten mit dem Wert Null ignoriert und die Replikatmessungen anschließend aus der „Alignment-Tabelle“ entfernt. Es bleibt nur das erste Replikat erhalten und die Intensität ist nun die Durchschnittliche aus allen Wiederholungen. Die restliche Tabelle wird nicht verändert. 

#### Remove row where features are not detected in consecutive files

Dieser Filter ist besonders für große Zeitreihen Datensätze von Nutzen. Hier können Sie angeben wie oft ein „Feature“ in einer Reihe gefunden werden muss, damit es erhalten bleibt. 


### Similar trends

Wenn Sie einen Trend eines “Features” bemerken und sich zeigen lassen wollen, welche “Features” einen ähnlichen Trendverlauf haben, müssen sie einen geringsten Korrelationsfaktor im Feld `Trend` angeben.  Wählen Sie zunächst eine Reihe und anschließend den Reiter `Similar trends`.
Durch positionieren des Maus Anzeigers auf einer der Linien, erscheinen unterhalb des Diagramms weiterführende Informationen zu dem „Feature“.

### Overview, Highest intensities and Cluster analysis tabs

All diese Reiter geben einen besseren Überblick über die „Alignment Tabelle“. In den meisten Fällen kann es sinnvoll sein, erst alle Filter auf die „Alignment-Tabelle“ anzuwenden und sich erst dann diesen Reitern zuzuwenden.
In diesen Reitern kann man die Intensitätsverläufe eines „Features“ betrachten, indem man den Mausanzeiger über einem Punkt  positioniert. Durch Auswahl eines Bereichs und anschließendes klicken erscheint im unteren Bereich eine Tabelle, in welcher alle „Features“ (aus diesem Bereich) aufgelistet sind. Durch Doppelklicken in den ausgewählten Bereich wird dieser vergrößert und durch nochmaliges Doppelklicken wieder zurückgesetzt. Nachdem die „Alignment-Tablle“ mit Namen versehen worden ist, erscheinen die benannten „Features“ auch im Dendrogramm.

### Annotation

Durch das Annotieren vesucht Features zu bennenen, wenn diese in der Spektrendatenbank zu finden sind. Wähle zunächst die Datenbank Datei und anschließend auf Annotate drucken. Nach ablauf der Berechnung erscheind eine Tabelle, die die Ergebnisse zeigt. Um Rechenzeit zu sparen, wird nur ein Feature aus jede Zeile der Alignment-Tabelle mit der Spektrendatenbank verglichen. Die Spalte "sample" sagt welche Probe für den Vergleich benutzt wurde. 