# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pearsoncoeff <- function(X, Y) {
    .Call(`_ntsworkflow_pearsoncoeff`, X, Y)
}

correlates_with <- function(aligned_intensities, row, coefficient) {
    .Call(`_ntsworkflow_correlates_with`, aligned_intensities, row, coefficient)
}

correlation <- function(aligned_intensities) {
    .Call(`_ntsworkflow_correlation`, aligned_intensities)
}

alignmentBfGC <- function(peaklistR, mz_dev, DeltaRT, mz_dev_unit) {
    .Call(`_ntsworkflow_alignmentBfGC`, peaklistR, mz_dev, DeltaRT, mz_dev_unit)
}

peakPickingBfGC <- function(mz, mz_step, XIC, scantime, min_intensity, sn, noisescans, peakwidth_min, peakwidth_max, maxPeaksPerSignal) {
    .Call(`_ntsworkflow_peakPickingBfGC`, mz, mz_step, XIC, scantime, min_intensity, sn, noisescans, peakwidth_min, peakwidth_max, maxPeaksPerSignal)
}

